### ISSUE TITLE
I have installed all tools 

### ISSUE THREAD

**Issue by Sahil07ii** [MR-S74RK/SUII-INSTA#33]
Please give me tool password 
![Screenshot_2023-03-24-20-43-44-46_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/127582898/227565823-727fd72e-9b34-4317-b774-a37669e9cfbc.jpg)

**Comment by ash554466** [comment]
Please give me password.

**Comment by MR-S74RK** [comment]
Its paid 200₹
If u need contact me
On insta or telegram
